encyclopedia/urls.py
from django.urls import path

from . import views

app_name ="enc"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>",views.article, name="article"),
    path("search/",views.search, name="search"),
    path("add/",views.add, name="add"),
    path("edit/<str:name>",views.edit, name="edit"),
    path("edit",views.saveedit, name="saveedit"),
    path("randompage",views.randompage, name="randompage"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import markdown2
import random
from django import forms

from . import util

class NewArticleForms( forms.Form) :
    article = forms.CharField(label="Найменування статті",widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label= "", widget=forms.Textarea(attrs={'class': 'form-control', 'style' :"height:100%; margin:5px 0px;"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def article(request, name):
    content = util.get_entry(name)
    if (content == None):
        return render(request, "encyclopedia/article.html", {
            "name": f'Стаття з назвою {name} не знайдена',
            "content": ""
        })
    md = markdown2.Markdown()
    result = md.convert(content)
    return render(request, "encyclopedia/article.html", {
        "name": name,
        "content": result
    })


def search(request):
    enc_list = []
    if request.method == "POST":
        form = request.POST
        wiki_list = util.list_entries()
        wiki_list_lower = []
        for wiki in wiki_list:
            wiki_list_lower.append(wiki.lower())
        if form['q'].lower() in wiki_list_lower:
            return HttpResponseRedirect(f"/wiki/{form['q']}")
        else:
            for wiki in wiki_list:
                if wiki.lower().find(form['q']) != -1:
                    enc_list.append(wiki)
            return render(request, "encyclopedia/search.html", {
                "entries": enc_list
                })

def add(request):
    if request.method == "POST":
        form = NewArticleForms(request.POST)
        if form.is_valid() :
            article = form.cleaned_data["article"]
            content = form.cleaned_data["content"]
            old_content=util.get_entry(article)
            if old_content==None:
                util.save_entry(article, content)
                return HttpResponseRedirect(f"/wiki/{article}")
            else:
                return render(request, "./encyclopedia/add.html", {
                        "form": form,
                        "error": f"Стаття з назвою '{article}' вже існує. Змініть назву."
                        })
        else:
            return render(request, "./encyclopedia/add.html", {
            "form": form
            })
    else:
        return render(request, "encyclopedia/add.html", {
            "form": NewArticleForms()
            })

def edit(request, name):
    content = util.get_entry(name)
    return render(request, "encyclopedia/edit.html", {
            "form": NewArticleForms({'article':name,'content':content}),
            "title_page":name
                })


def saveedit(request):
    if request.method == "POST":
        form = NewArticleForms(request.POST)
        if form.is_valid() :
            article = form.cleaned_data["article"]
            content = form.cleaned_data["content"]
            util.save_entry(article, content)
            return HttpResponseRedirect(f"/wiki/{article}")

def randompage(request):
    pages =  util.list_entries()
    rand = random.choice(pages)
    return HttpResponseRedirect(f"/wiki/{rand}")

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Дадати нову статтю
{% endblock %}

{% block body %}
<form action=" {%url 'enc:add'%}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1"></span>
          <input
          class="form-control form-control-dark w-200"
          type="text"
          name="q"
          placeholder="знайти статтю"
        />       
     </form>
{% endblock %}

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{name}}
{% endblock %}

{% block body %}
<div style="display:flex; justify-content:space-between">
    <h1>{{name}}</h1> 
    <button type="button" class="btn btn-outline-success" >
      <a href="/edit/{{name}}" > 
      редагувати 
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
    </svg>
  </a>
  </button>
  </div>
    <div>
      {{content|safe}}
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Редагування сторінки {{title_page}}
{% endblock %}

{% block body %}



<form action="{%url 'enc:saveedit'%}" method="post">
    {% csrf_token %}
    <div class="card" style="height: 100%;">
      <div class="card-body">
        <h5 class="card-title">
          <h3>Редагування '{{title_page}}'</h3>
        </h5>
        {% if error %}
          <h6 style="color:red;">{{error}}</h6>
        {% endif %}
        <p class="card-text">
        {{form}}
</p>
  <button type="submit" class="btn btn-primary" fullwidth>Зберегти статтю</button>
</div>
</div>

</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Енциклопедія
{% endblock %}

{% block body %}
    <h1>Всі сторінки</h1>

    <ul>
        {% for entry in entries %}
             <li><a href="/wiki/{{entry|safe}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
     <div style="display:flex;">
      <div class="sidebar col-lg-2 col-md-3" >
        <h2>Wiki</h2>

        <form action=" {%url 'enc:search'%}" method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1"><svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    fill="currentColor"
                    class="bi bi-search"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"
                    />
                  </svg></span>
                  <input
                  class="form-control form-control-dark w-200"
                  type="text"
                  name="q"
                  placeholder="знайти статтю"
                />       
             </form>
     </div>
       <div>
          <a href="{% url 'enc:index' %}">Початкова сторінка</a>
        </div>
        <div><a href="{% url 'enc:add' %}">Створити статтю</a></div>
        <div><a href="{% url 'enc:randompage' %}">Довільна стаття</a></div>
        {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9">
      </header>  
        {% block body %} {% endblock %}</div>
  </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Енциклопедія
{% endblock %}

{% block body %}
    <h1>Знайдені сторінки за запитом</h1>

    <ul>
        {% for entry in entries %}
             <li><a href="/wiki/{{entry|safe}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}